kind: Service
apiVersion: v1
metadata:
  name: frontend
  labels:
    run: frontend
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 4200
    targetPort: 4200
  selector:
    run: frontend
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      run: frontend
  replicas: 1
  template:
    metadata:
      labels:
        run: frontend
    spec:
      containers:
      - name: frontend
        image: darryl3223/frontend:latest
        ports:
        - containerPort: 4200