kind: Service
apiVersion: v1
metadata:
  name: frontend
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 4200
    targetPort: 4200
  selector:
    app: frontend
    component: frontend
---
kind: StatefulSet
apiVersion: apps/v1beta1
metadata:
  name: frontend
spec:
  serviceName: "frontend"
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend
        component: frontend
    spec:
      containers:
      - name: frontend
        image: darryl3223/frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 4200