kind: Service
apiVersion: v1
metadata:
  name: backend
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  selector:
    app: backend
    component: backend
---
kind: StatefulSet
apiVersion: apps/v1beta1
metadata:
  name: backend
spec:
  serviceName: "backend"
  replicas: 1
  template:
    metadata:
      labels:
        app: backend
        component: backend
    spec:
      containers:
      - name: backend
        image: darryl3223/backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080