kind: Service
apiVersion: v1
metadata:
  name: backend
  labels:
    run: backend
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  selector:
    run: backend
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      run: backend
  replicas: 1
  template:
    metadata:
      labels:
        run: backend
    spec:
      containers:
      - name: backend
        image: darryl3223/backend:latest
        ports:
        - containerPort: 8080